substitutions:
  name: transit-tracker
  friendly_name: Transit Tracker
  project_version: "dev"

esphome:
  name: ${name}
  name_add_mac_suffix: true
  friendly_name: ${friendly_name}
  project:
    name: "a10kiloham.Transit Tracker"
    version: ${project_version}

ota:
  - platform: esphome

packages:
  a10kiloham.Transit Tracker: github://a10kiloham/transit-tracker/firmware/transit-tracker.yaml@main

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

color:
  - id: my_red
    hex: "F50046"
  - id: my_green
    hex: "20FF00"
  - id: my_orange
    hex: "ff5900"
  - id: rapidride_red
    hex: "F50046"
  - id: numbered_yellow
    hex: "FFD700"
  - id: headsign_white
    hex: "E0E0E0"
  - id: time_grey
    hex: "B0B0B0"
  - id: realtime_green
    hex: "20FF00"

transit_tracker:
  id: tracker
  # change to your API server
  base_url: "wss://0.0.0.0/"
  time_display: "arrival"
  show_units: "long"
  list_mode: "sequential"
  scroll_headsigns: true
  headsign_color: my_green
  route_display: numbered
  numbered_color: my_red
  time_color: headsign_white
  
  show_realtime_icon: false
  limit: 6
  stops:
    - stop_id: "tfl:940GZZLUHTD"
      routes:
        - "tfl:northern-outbound"
        - "tfl:northern-inbound"
  styles:
    - route_id: "tfl:northern-outbound"
      name: ""
      color: my_orange
    - route_id: "tfl:northern-inbound"
      name: ""
      color: my_red