substitutions:
  name: transit-tracker-dc2218
  friendly_name: Transit Tracker dc2218
  project_version: "dev"

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  project:
    name: "a10kiloham.Transit Tracker"
    version: ${project_version}

ota:
  - platform: esphome

packages:
  a10kiloham.Transit Tracker: github://a10kiloham/transit-tracker/firmware/transit-tracker.yaml@main

dashboard_import:
  package_import_url: github://a10kiloham/transit-tracker/firmware/transit-tracker.yaml@main

external_components:
  - source: github://avwuff/ESPHome-HUB75-MatrixDisplayWrapper@4fc1f26500b97a39693cd8af4ba2abb75f83ce0b
    refresh: 0s
  - source: github://a10kiloham/esphome-transit-tracker@main
    refresh: 0s
  - source: github://tjhorner/esphome-custom-components@c57ffd46fcf30badb2838421e8ff6cbeb9c1dd06
    components: [ lis3dh, project_version ]
    refresh: 0s
    
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

transit_tracker:
  id: tracker
  base_url: "wss://tfl.xdca.com/"
  time_display: "arrival"
  show_units: "long"
  list_mode: "sequential"
  scroll_headsigns: true
  stops:
    - stop_id: "tfl:940GZZLUHTD"
      routes:
        - "tfl:northern-outbound"
        - "tfl:northern-inbound"
  styles:
    - route_id: "tfl:northern-outbound"
      name: ""
      color: "c_001AFF"
    - route_id: "tfl:northern-inbound"
      name: ""
      color: "c_FF0037"